### ISSUE TITLE
Slow queries - FR

### ISSUE THREAD

**Issue by lefred** [charles-001/dolphie#10]
It would be great to have a panel that check in PFS the slow queries ans then display some metadata and Query Execution Plan for those queries.

See https://lefred.be/content/mysql-8-0-if-i-should-optimize-only-one-query-on-my-application-which-one-should-it-be/ for ideas

**Comment by charles-001** [comment]
The thing with PFS data is that it aggregates data from the time MySQL starts. Dolphie is built to be a real time view of what's happening so not sure if I want to include possible stale/inaccurate data.

**Comment by charles-001** [comment]
Closing this since it's been 2 weeks with no response
