### ISSUE TITLE
Indexes panel - FR

### ISSUE THREAD

**Issue by lefred** [charles-001/dolphie#12]
It would be great to have a panel to see/manage duplicate indexes, unused indexes, invisible indexes, ...

**Comment by charles-001** [comment]
I don't think this is a feature that Dolphie needs to support mainly because that's a simple SELECT query from `sys` schema.  Most users would want to easily copy/paste, have a report, etc, which would prompt them to run a SELECT anyway.

**Comment by charles-001** [comment]
Closing this since it's been 2 weeks with no response
