### ISSUE TITLE
add hostname and port in the TopBar

### ISSUE THREAD

**Issue by lefred** [charles-001/dolphie#15]
Currently Top Bar is using the host used to connect.

But maybe you connect using port forwarding or ssh tunnel, or using sandboxes... so it would be nice to see the details used to connect (host and port) but also the value of @@hostname and @@port

It would be great to see:

`127.0.0.1:3307 - dell:3306`

**Comment by charles-001** [comment]
I like the idea @lefred - only concern is how long that section of the topbar can get. Hostnames can generally be very long. I'm 100% fine with adding hostname/port from @@hostname/@@port, but adding the other stuff may be too much.

**Comment by charles-001** [comment]
Decided to go ahead and only support @@hostname/@@port for the header. If you feel strongly enough about adding the connection information outside of MySQL, we can discuss further. Thank you for your suggestion!

This will be included in v3.0.3
