### ISSUE TITLE
Add support for Percona XtraDB Cluster 

### ISSUE THREAD

**Issue by bds-congnguyen** [charles-001/dolphie#22]
The Percona Multi-source replication means that you can write to any node and be sure that the write will be consistent for all nodes in the cluster. https://docs.percona.com/percona-xtradb-cluster/5.7/features/highavailability.html
it doesn't use master-slave show run command
```
show slave status;
```
will return empty and it cause `No data to display! This host is not a replica and has no replicas connected`
show I suggest add feature to get cluster status by `wsrep_local_state_comment`

```
mysql> SHOW STATUS LIKE 'wsrep_local_state_comment';
+---------------------------+--------+
| Variable_name             | Value  |
+---------------------------+--------+
| wsrep_local_state_comment | Synced |
+---------------------------+--------+
1 row in set (0.00 sec)
```

**Comment by charles-001** [comment]
Hey @bds-congnguyen - there's probably a lot that can be displayed for clustering besides that... I just don't have an environment setup/knowledge background to support it. If you want the replication panel to just simply display that, that's fine.

**Comment by charles-001** [comment]
This is in v3.0.8
