### ISSUE TITLE
[BUG] Crash on replication panel for source of Replicaset

### ISSUE THREAD

**Issue by valentintraen** [charles-001/dolphie#23]
Hi !

Dolphie crashes when launched on the source of a Replicaset (replication panel). Other panels work without problem.
No problem on replica.

Percona Server 8.0.29

![screen_1](https://github.com/charles-001/dolphie/assets/8438614/78612abe-0a35-45c0-9f26-9fc2bf1212ae)
![screen_2](https://github.com/charles-001/dolphie/assets/8438614/d6bcfcc9-9cc2-493b-9bc7-7027f71a6a3f)
![screen_3](https://github.com/charles-001/dolphie/assets/8438614/39bff2dc-37e4-46e3-9f69-6696fb71b9c3)

**Comment by charles-001** [comment]
Hi @valentintraen - thanks for your bug report! I've fixed it in v3.0.9

**Comment by valentintraen** [comment]
Thank you !
