### ISSUE TITLE
[BUG] Crash when seconds_behind_master is null

### ISSUE THREAD

**Issue by valentintraen** [charles-001/dolphie#27]
Hi again !

When seconds_behind_master is not an INT (if master has been stopped for example), Dolphie crashes : 

![screen_7](https://github.com/charles-001/dolphie/assets/8438614/43c91784-00b3-4b1b-804a-f4144311c5f8)

![screen_8](https://github.com/charles-001/dolphie/assets/8438614/812549f8-b70f-4843-bf95-af703b11a2f5)
![screen_9](https://github.com/charles-001/dolphie/assets/8438614/5e373227-de53-4947-a6db-e9be94f2f798)

Percona Server 5.7.39

**Comment by charles-001** [comment]
Thank you @valentintraen for your bug report! This will be included in v3.0.10
