### ISSUE TITLE
[Improvement] m command and MySQL 5.6

### ISSUE THREAD

**Issue by valentintraen** [charles-001/dolphie#28]
I tried m command on MySQL 5.6 and Dolphie crashes because of the absence of the sys.memory_by_user_by_current_bytes view. I don't think that memory views are present in MySQL 5.6 so, as MySQL 5.6 will soon no longer maintained, maybe it would be interesting not to display this information for this version of MySQL.

**Comment by charles-001** [comment]
Thank you for your bug report! This will be in v3.0.10
