### ISSUE TITLE
 Access denied; you need (at least one of) the PROCESS privilege(s) for this operation

### ISSUE THREAD

**Issue by ppcharli** [charles-001/dolphie#35]
#dolphie -V
3.1.3
#mysql -V
mysql  Ver 8.0.33-25.1 for Linux on x86_64 (Percona XtraDB Cluster (GPL), Release rel25, Revision 0c56202, WSREP version 26.1.4.3)

#dolphie -u root -h localhost
  Error
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Failed to execute query
  /* dolphie */
          SELECT
              NAME,
              COUNT
          FROM
              information_schema.INNODB_METRICS
          WHERE
             name IN ('adaptive_hash_searches', 'adaptive_hash_searches_btree', 'trx_rseg_history_len')
  Access denied; you need (at least one of) the PROCESS privilege(s) for this operation

However, executing the same query with mysql works

 #mysql -u root -h localhost
mysql>  SELECT
    ->               NAME,
    ->               COUNT
    ->           FROM
    ->               information_schema.INNODB_METRICS
    ->           WHERE
    ->               name IN ('adaptive_hash_searches', 'adaptive_hash_searches_btree', 'trx_rseg_history_len');
+------------------------------+-------+
| NAME                         | COUNT |
+------------------------------+-------+
| trx_rseg_history_len         |     0 |
| adaptive_hash_searches       | 35910 |
| adaptive_hash_searches_btree | 64100 |
+------------------------------+-------+
3 rows in set (0.01 sec)

Thanks,

**Comment by charles-001** [comment]
Hi @ppcharli - thanks for your bug report! That's a strange issue as I've never seen this happen before. Since you're connecting from root, I'd assume it has full privileges. Can you try and create a new user and try with that?

**Comment by ppcharli** [comment]
Hi, creating another user works fine
Thanks

**Comment by charles-001** [comment]
Gotcha - must be something with your root user then. Glad it's working now :)
