### ISSUE TITLE
Usage of youtube-dl/video extras

### ISSUE THREAD

**Issue by flopex** [charles-001/dolphie#39]
What is 'youtube-dl', or extra 'video', being used for?
https://github.com/charles-001/dolphie/blob/190d1904cbea9e7559cbf00429b5deaf2df701ba/poetry.lock#L348

**Comment by charles-001** [comment]
Hi @flopex - this is a dependency for `plotext` as you can see [here](https://github.com/piccolomo/plotext/blob/master/setup.py).
