### ISSUE TITLE
View "sys.innodb_lock_waits" references invalid table(s) or column(s)

### ISSUE THREAD

**Issue by klemenb** [charles-001/dolphie#43]
Hi!

I am seeing the error in the attachment when trying to connect to a MySQL server with the following version string:

`mysql  Ver 8.0.34-26 for Linux on x86_64 (Percona Server (GPL), Release '26', Revision '5dfee7bd')`

Dolphie 3.1.2 worked and after upgrading to 3.3.1 this error appeared. I am guessing this is related to the added "Locks" panel in 3.2.0.

![failed_to_execute_query](https://github.com/charles-001/dolphie/assets/2099210/19119a99-3357-4e67-b174-22695b996300)

**Comment by charles-001** [comment]
Hi @klemenb - can you check to see if you have the `sys` schema and if so, provide the output of `SHOW CREATE TABLE sys.innodb_lock_waits`? This isn't an issue with Dolphie, but with your MySQL server and/or permissions.

**Comment by klemenb** [comment]
Hi, sorry, yes the schema was there and I thought it was something that either Percona changed or was changed in a recent MySQL release. It was indeed a permission issue. Sorry for spamming your issue tracker and thank you for your help.

**Comment by charles-001** [comment]
No worries! Feel free to reach out anytime :)
