### ISSUE TITLE
Feature request: Metadata locks panel

### ISSUE THREAD

**Issue by charles-001** [charles-001/dolphie#49]
I'm looking to add a metadata lock panel and think this query works well - anyone have any thoughts on if this is the right approach?
```sql
SELECT
    OBJECT_INSTANCE_BEGIN AS id,
    OBJECT_TYPE,
    OBJECT_SCHEMA,
    OBJECT_NAME,
    LOCK_TYPE,
    LOCK_STATUS,
    SOURCE,
    PROCESSLIST_ID,
    PROCESSLIST_USER,
    PROCESSLIST_TIME,
    PROCESSLIST_INFO
FROM
    `performance_schema`.`metadata_locks` mlb JOIN
    `performance_schema`.`threads` t ON mlb.OWNER_THREAD_ID = t.THREAD_ID
WHERE
    NOT (OBJECT_TYPE = 'TABLE' AND LOCK_STATUS = 'GRANTED') AND
    OBJECT_TYPE != 'COLUMN STATISTICS'
ORDER BY
    PROCESSLIST_TIME DESC
```
This is what the result looks like:
<img width="1939" alt="Screenshot 2024-02-22 at 8 14 09 PM" src="https://github.com/charles-001/dolphie/assets/13244625/ee22904c-834e-4e0c-8e23-e08789012b2f">

**Comment by aadant** [comment]
I think you should add the thread name. It is interesting to know it is a replication thread versus a regular connection.

The first filter is not obvious, if the lock was granted and is held by the thread, it is interesting to know it is holding that lock for long time (example a python notebook opening a transaction by mistake !). Maybe sort by age desc and allow to filter / sort on the table name ?

**Comment by aadant** [comment]
@lefred please chime in :)

**Comment by charles-001** [comment]
@aadant - good idea on showing the thread name. I've added that under `Thread Source` column. I'm stripping out the `thread/sql`, `thread/innodb` to conserve space.

As for showing all `GRANTED` locks for `TABLE`, I don't think that's feasible due to how many rows will be created. On my servers for instance, I can have 2,000 of them that are constantly changing each refresh interval. That isn't digestible for anyone. I don't really want to create filters for this panel as I don't think it's needed, but if you'd like to take a jab at working w/ Dolphie's code, you can. For now, I think a good compromise is to change the WHERE clause to something like this to make the panel digestible:
```sql
NOT (OBJECT_TYPE = 'TABLE' AND LOCK_STATUS = 'GRANTED' AND PROCESSLIST_TIME <= 2)
``` 
This will do what I originally wanted while showing the long-held locks like you want. Thoughts?

**Comment by aadant** [comment]
What about grouping them by thread id and lock type, status and group concat for tables ?

**Comment by charles-001** [comment]
Not a bad idea, but Dolphie's table won't be able to show a lot of the tables concatted.

**Comment by charles-001** [comment]
I changed the WHERE clause to this which I think limits it a bit better for filtering out spam:
```sql
NOT (
    OBJECT_TYPE = 'TABLE' AND
    LOCK_STATUS = 'GRANTED' AND
    LOCK_TYPE = 'SHARED_READ' AND
    PROCESSLIST_TIME <= 2
) AND
```
I can't see a reason wanting to see any metalocks that relate to the above information below 2 seconds. Can you?

**Comment by charles-001** [comment]
@aadant - I also just added the filters that the processlist panel uses. I didn't realize how easy it'd be ;)

**Comment by charles-001** [comment]
```sql
SELECT
            ANY_VALUE(OBJECT_INSTANCE_BEGIN) AS id,
            ANY_VALUE(OBJECT_TYPE) AS OBJECT_TYPE,
            ANY_VALUE(OBJECT_SCHEMA) AS OBJECT_SCHEMA,
            CASE
                WHEN COUNT(DISTINCT OBJECT_NAME) = 1 THEN ANY_VALUE(OBJECT_NAME)
                WHEN COUNT(DISTINCT OBJECT_NAME) = 0 THEN NULL
                ELSE CONCAT(COUNT(DISTINCT OBJECT_NAME), ' objects')
            END AS OBJECT_NAME,
            LOCK_TYPE,
            LOCK_STATUS,
            ANY_VALUE(SOURCE) AS CODE_SOURCE,
            ANY_VALUE(NAME) AS THREAD_SOURCE,
            ANY_VALUE(PROCESSLIST_ID) AS PROCESSLIST_ID,
            ANY_VALUE(PROCESSLIST_USER) AS PROCESSLIST_USER,
            ANY_VALUE(PROCESSLIST_TIME) AS PROCESSLIST_TIME,
            ANY_VALUE(PROCESSLIST_INFO) AS PROCESSLIST_INFO
        FROM
            `performance_schema`.`metadata_locks` mlb JOIN
            `performance_schema`.`threads` t ON mlb.OWNER_THREAD_ID = t.THREAD_ID
        WHERE
            NOT (
                OBJECT_TYPE = 'TABLE' AND
                LOCK_STATUS = 'GRANTED' AND
                LOCK_TYPE LIKE 'SHARED%' AND
                PROCESSLIST_TIME <= 2
            ) AND
            OBJECT_TYPE != 'COLUMN STATISTICS'
        GROUP BY
            THREAD_ID,
            LOCK_TYPE,
            LOCK_STATUS
```
This seems to really cut down on garbage and from my testing, looks good.

**Comment by charles-001** [comment]
```sql
SELECT
    ANY_VALUE(OBJECT_INSTANCE_BEGIN) AS id,
    ANY_VALUE(OBJECT_TYPE) AS OBJECT_TYPE,
    ANY_VALUE(OBJECT_SCHEMA) AS OBJECT_SCHEMA,
    CASE
        WHEN COUNT(DISTINCT OBJECT_NAME) = 1 THEN ANY_VALUE(OBJECT_NAME)
        WHEN COUNT(DISTINCT OBJECT_NAME) = 0 THEN NULL
        ELSE CONCAT(COUNT(DISTINCT OBJECT_NAME), ' objects')
    END AS OBJECT_NAME,
    LOCK_TYPE,
    LOCK_STATUS,
    ANY_VALUE(SOURCE) AS CODE_SOURCE,
    ANY_VALUE(NAME) AS THREAD_SOURCE,
    ANY_VALUE(PROCESSLIST_ID) AS PROCESSLIST_ID,
    ANY_VALUE(PROCESSLIST_USER) AS PROCESSLIST_USER,
    ANY_VALUE(PROCESSLIST_TIME) AS PROCESSLIST_TIME,
    ANY_VALUE(PROCESSLIST_INFO) AS PROCESSLIST_INFO
FROM
    `performance_schema`.`metadata_locks` mlb JOIN
    `performance_schema`.`threads` t ON mlb.OWNER_THREAD_ID = t.THREAD_ID
WHERE
    NOT (
        OBJECT_TYPE = 'TABLE' AND
        LOCK_STATUS = 'GRANTED' AND
        LOCK_TYPE LIKE 'SHARED%' AND
        PROCESSLIST_TIME <= 2
    ) AND
    OBJECT_TYPE != 'COLUMN STATISTICS'
GROUP BY
    THREAD_ID,
    LOCK_TYPE,
    LOCK_STATUS
```
This seems to really cut down on garbage and from my testing, looks good.

**Comment by charles-001** [comment]
This is now in v4.3.0

**Comment by aadant** [comment]
I see Object Name : 2 objects. No added value really :-)

If I run the query

```
select * from performance_schema.metadata_locks where owner_thread_id in (select thread_id from performance_schema.threads where name like '%worker%');
``` 
I can see which tables are being written by replication (maybe a different panel ?)

**Comment by charles-001** [comment]
@aadant - yes, I do that because that field will only allow one table to be listed due to space constraint. If there's only one, Dolphie will show it, but if there's more than one, it shows the count of objects as you see.

If you absolutely need to see that, then logging into a mysql client is probably best for more in-depth troubleshooting.

**Comment by aadant** [comment]
There are several issues in this UI design 

the column name should match the performance schema. Rather than hiding information or tranform it you should display it. Maybe increase the column or just allow duplicates for the same thread (same color per thread id) with a filter to display replication threads only.

this is particularly useful to track metadata locks

**Comment by aadant** [comment]
I mean filter by thread name, table name

**Comment by charles-001** [comment]
Well, you said above to group concat it above then trim and now you're saying to have a row per object name so it's displayed as it is in PFS - so which one is it? When I was doing my testing, having it display the same row with a different object name was too much spam. Condensing it the way I did made the data displayed much more digestible. Sure, I can't see which tables are a part of the metadata lock, but what really matters is seeing the overall locking statuses which the panel does nicely.

**Comment by charles-001** [comment]
I've updated the datatable to now `GROUP_CONCAT` the values for `object_name` and list them as a new line for the row with a set height. This lets me be able to populate only 1 row, but with multiple lines for the `object_name` so the datable isn't filled with the same text for each row that has the same `object_name`. I also made the datatable zebra-striped so it's easier to read. I'll look to release this change in the next release which will probably be on Sunday night.

In the meantime, if you want to test this change @aadant, you can by cloning this repo, running `poetry install`, then `poetry run dolphie`

**Comment by charles-001** [comment]
I've pushed the new version out @aadant so you won't need to run it via poetry to test my changes.
