### ISSUE TITLE
Allow paging for the error log screen - FR

### ISSUE THREAD

**Issue by lefred** [charles-001/dolphie#6]
When entering the error log panel, if there are a lot of entries this can take a while and if we press some keys to exit it, we got a stack trace.
If could be nice to have some paging mechanism and have the possibility to reach the end immediately.
![Screenshot from 2023-08-16 19-04-57](https://github.com/charles-001/dolphie/assets/609675/867a5d37-20ca-48ad-9c29-0d7b74064efe)

**Comment by charles-001** [comment]
I have fixed the bug you shared, but am not sure we need to paginate after my latest changes in 3.0.2. Let me know if a lot of events is still an issue.

**Comment by charles-001** [comment]
Closing this. I don't think pagination is required with how much better performance there is now with 3.0.2
