### ISSUE TITLE
Display details of thread crashes

### ISSUE THREAD

**Issue by choadrocker** [charles-001/dolphie#62]
On large queries and or large windows, dolphie crashes with:
`AttributeError: 'NoneType' object has no attribute 'splitlines'`

I have attached a traceback

And thanks for the great tool!

**Comment by choadrocker** [comment]
[dolphie_crash.txt.zip](https://github.com/charles-001/dolphie/files/15155320/dolphie_crash.txt.zip)

**Comment by charles-001** [comment]
Hi @choadrocker - thanks for reporting this! I've seen this issue before and honestly, I don't see _why_ it's happening. It seems like it's a bug in Rich's `Syntax` module, but I'm not quite sure. Is it easily reproducible for you? I've only ran into it once.

**Comment by choadrocker** [comment]
I can reproduce it

What will be helpful to provide?

**Comment by charles-001** [comment]
That's a good question because the traceback doesn't show me what line of Dolphie itself is causing the issue, heh. Since it's easily reproducible for you, any chance you can change the code to not use `Syntax` and see if that fixes it?

**Comment by choadrocker** [comment]
Ill give it a shot and let you know. 
It also may have choked on binary data

**Comment by charles-001** [comment]
That's a good point @choadrocker - it could be binary data. The more I think about it, I don't think `Syntax` is at fault because all queries are processed with it to format in processlist panel. I wish the traceback told us what code in Dolphie is at fault...

**Comment by charles-001** [comment]
@choadrocker - I think I fixed this. Can you try it out on your end?

Please do these steps:
1. Checkout main branch of Dolphie
2. Run `poetry install`
3. Run `poetry run dolphie` with your normal parameters

**Comment by charles-001** [comment]
@choadrocker - following up on this with you as I'd like to get this fix pushed to a new version if it works. Any chance you can test on your end soon?

**Comment by charles-001** [comment]
@choadrocker - pinging you one last time for your input before I release a new version with this fix

**Comment by charles-001** [comment]
This has been pushed to 5.0.2

**Comment by choadrocker** [comment]
Sorry I missed these! Thanks for the help!

**Comment by charles-001** [comment]
No worries - did you by chance get to test the change and verify it fixes your issue?
