### ISSUE TITLE
Dolphie 5.0.2 with MariaDB 10.3

### ISSUE THREAD

**Issue by Esysteme** [charles-001/dolphie#64]
![Capture d’écran du 2024-05-27 17-36-21](https://github.com/charles-001/dolphie/assets/2485014/192adc26-900e-4ebe-8750-8110867b1678)

**Comment by charles-001** [comment]
Hi @Esysteme - MariaDB 10.3 was EOL in May of 2023. I don't think I should support that old of a version as a new change. Is it possibe for you to upgrade? Seems the `connection_type` column was added in 10.5

**Comment by Esysteme** [comment]
Yes, in fact i work for many different client, i use dolphie a first approach, if you ok i will make a PR to support all from mysql 5.5, (i hate python but anyway)

**Comment by charles-001** [comment]
Sure, I can accept a PR that adds it.

**Comment by charles-001** [comment]
Closing this since you're creating a PR in the future
