### ISSUE TITLE
Don't use `os.getloadavg()` on Windows

### ISSUE THREAD

**Issue by jycor** [charles-001/dolphie#77]
Installed dolphie through `pip`, and I'm getting a `AttributeError: module 'os' has no attribute 'getloadavg' `
It seems like Python's `os` module does not support `getloadavg()` on Windows machines.

Python Version: `3.11.4`

**Comment by charles-001** [comment]
Hi @jycor - I don't know why I'm using `os` there when I use `pustil` for everything else. This will be fixed in the next version. Thank you for your bug report!

**Comment by charles-001** [comment]
Actually, just went ahead and pushed a new version since this is a crashing bug. Let me know if it fixes your issue!

**Comment by jycor** [comment]
Yep, works now! Thanks for the quick fix!
