### ISSUE TITLE
Textual Error : Docker

### ISSUE THREAD

**Issue by jdelramirez** [charles-001/dolphie#80]
Good morning, first of all, thank you for the great work you have done for this tool! On the other hand, I am trying to run it in a container and it gives me the following error:

![image](https://github.com/user-attachments/assets/5b91a1aa-32c1-4117-9266-527a34b9d77a)

What can i do ? 

Thanks!!

**Comment by charles-001** [comment]
Hi @jdelramirez - what version of Dolphie are you using and did you pull from `ghcr.io/charles-001/dolphie:latest`?

**Comment by jdelramirez** [comment]
Thanks for your reply! sure the versión is : 

root@6f6b0aa3ed94:/app# dolphie --version
6.5.4

and i did the pull to the latest : podman pull ghcr.io/charles-001/dolphie:latest

**Comment by jdelramirez** [comment]
ok thanks anyway hehe, can i use the tool without the start parameter :  --tab-setup ?

**Comment by charles-001** [comment]
Yeah, you can use any parameters you want (if it works lol)

**Comment by charles-001** [comment]
These were my steps btw:
```shell
docker pull ghcr.io/charles-001/dolphie:latest
docker run -dit --name dolphie ghcr.io/charles-001/dolphie:latest
docker exec -it dolphie /bin/bash
root@bf53541ca7ef:/app# dolphie --tab-setup
```

**Comment by jdelramirez** [comment]
Thanks for your help Charles, I'll try it with Docker, because I'm using Podman, but it should be the same.

**Comment by charles-001** [comment]
Let me know if that works for you!
