### ISSUE TITLE
Suggestion: Panel identifier shown

### ISSUE THREAD

**Issue by CodeBleu** [charles-001/dolphie#83]
Not a big deal, but was wondering if the actual hotkey/id of the panel could be shown so it's easier to know what to toggle off and on without having to remember or go to the `?`

Similar to how [btop](https://github.com/aristocratos/btop) works
![image](https://github.com/user-attachments/assets/0416d8f8-0943-4d30-8fa3-c87bd922d856)

**Comment by charles-001** [comment]
Hi @CodeBleu - how does this work for you?
<img width="2021" alt="Screenshot 2024-12-02 at 3 10 54 PM" src="https://github.com/user-attachments/assets/26df7af6-9cf6-41f1-8d10-518663603c12">

**Comment by CodeBleu** [comment]
That looks great! Thanks!

**Comment by charles-001** [comment]
This is now in version `6.6.3`
