### ISSUE TITLE
REPLICA keyword not supported in older versions of mysql/mariadb

### ISSUE THREAD

**Issue by gaetan-pnvt** [charles-001/dolphie#84]
Great software!

https://mariadb.com/kb/en/show-replica-status/

Could we add support to the "SLAVE" keyword to allow backward compatibility with older versions ( versions < mariadb 10.5) ?

The terms master and slave have historically been used in replication, and MariaDB has begun the process of adding primary and replica synonyms. The old terms will continue to be used to maintain backward compatibility - see [MDEV-18777](https://jira.mariadb.org/browse/MDEV-18777) to follow progress on this effort.

**Comment by charles-001** [comment]
Hi Gaëtan,

Thank you for the compliment! I looked at the code and it seems I'm already using the `SLAVE` terminology for MariaDB (see [here](https://github.com/charles-001/dolphie/blob/ddcc9464e89d26c0d663f56ba77e4a9180c09f1d/dolphie/Panels/replication_panel.py#L570)). Can you point me to what part of Dolphie is failing?

**Comment by gaetan-pnvt** [comment]
Btw, I'm using version dolphie --version 6.6.3 (installed on MacOS via brew)

At login I get the message: 
Failed to execute query: 
/* dolphie */ SHOW REPLICA STATUS
You have an error in your SQL syntax; check the manual ....

The query is not supported on MariDB 10.3.

**Comment by gaetan-pnvt** [comment]
10.3.27-MariaDB-0+deb10u1-log

**Comment by charles-001** [comment]
Hm.. this is very strange. I spoofed my `version_comment` and `version` with yours and it's trying to run `SHOW SLAVE STATUS` as seen in the screenshot. 
<img width="1885" alt="Screenshot 2024-12-05 at 4 13 18 PM" src="https://github.com/user-attachments/assets/14a79e46-dff5-4c4d-b7bf-9f5a77896475">

**Comment by charles-001** [comment]
@gaetan-pnvt - Do you have the replicas panel open when this happens?

**Comment by charles-001** [comment]
I've created a new branch called `6.6.4` that I think fixed this issue. Can you follow these steps and test it out?

git clone the repo
git checkout 6.6.4
poetry install
poetry run dolphie <options>

**Comment by charles-001** [comment]
Since you haven't responded, I went ahead and released a new version (6.7.0) that hopefully fixes this. Let me know if the issue persists.
