### ISSUE TITLE
[BUG] Percona Server for MySQL displayed as Mariadb

### ISSUE THREAD

**Issue by valentintraen** [charles-001/dolphie#87]
Hi,

With the last version, my PS instances are displayed as Mariadb instances :

![image](https://github.com/user-attachments/assets/0bb48165-1cc1-45b3-b80e-028b0e8f3aeb)

![image](https://github.com/user-attachments/assets/df59646b-a7c5-4deb-9d15-b520c543305a)

**Comment by charles-001** [comment]
Hi @valentintraen - that is... odd. I am seeing Percona Server for my hosts. When you run `SHOW GLOBAL VARIABLES`, are there any variables that have `aria` in them? See how I determine if it's MariaDB [here](https://github.com/charles-001/dolphie/blob/f65d408d571a057a77259a4c59a84092cda2d81f/dolphie/Dolphie.py#L245)

**Comment by valentintraen** [comment]
Ahaha you couldn't guess that... aria is in "show variables"

![image](https://github.com/user-attachments/assets/75f9aa87-4fde-4251-9b6b-95dc9be85fa1)

**Comment by charles-001** [comment]
I see the issue :) Just pushed `6.7.2` - give that a try

**Comment by valentintraen** [comment]
Perfect ! Thank you 
![image](https://github.com/user-attachments/assets/c87d313f-10bd-4a99-b8ba-7775f4632645)

**Comment by charles-001** [comment]
Thanks for letting me know!
