### ISSUE TITLE
Obfuscate password is process output

### ISSUE THREAD

**Issue by CodeBleu** [charles-001/dolphie#88]
Can you obfuscate the password for the process output please?
![image](https://github.com/user-attachments/assets/a3a2cf46-520e-40aa-8786-8da7a40c9d9b)

**Comment by charles-001** [comment]
Hi @CodeBleu - I'd highly suggest not putting passwords on the command-line as a parameter. Dolphie has _many_ ways to utilize credentials. Maybe take a look at what's available, including `--tab-setup` option and see if you still want this request.

**Comment by CodeBleu** [comment]
> Hi @CodeBleu - I'd highly suggest not putting passwords on the command-line as a parameter. Dolphie has _many_ ways to utilize credentials. Maybe take a look at what's available, including `--tab-setup` option and see if you still want this request. 

I agree that passing it via command line is not good...however it would still be nice to have that obfuscated when it is used.  With having other options, like you mentioned, I understand if you don't want to implement this.

I'm using another tool (mydumper), and it will obfuscate the password that is passed via command line, and was hoping dolphie could too.

**Comment by charles-001** [comment]
To be honest, I'm not even sure how to do that in Python.

**Comment by CodeBleu** [comment]
Im seeing stuff about LD_PRELOAD, but prob not worth it.  Please feel free to close this issue if you want.

**Comment by charles-001** [comment]
Yeah, agreed.
